apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx
      image: nginx:1.14.0
      volumeMounts:
      - mountPath: "/usr/share/nginx"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: nginx-claim
